# Generated by Django 2.1.5 on 2019-01-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=200)),
                ('msg_type', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
                ('frequency', models.IntegerField()),
            ],
        ),
    ]
