# Generated by Django 2.1.7 on 2019-02-27 21:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190227_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
