# Generated by Django 2.1.7 on 2019-02-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horizon',
            name='accel',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
